### ISSUE TITLE
support XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by emorrp1** [dashohoxha/egpg#60]
Just a request to essentially use ~/.config/egpg rather than ~/.egpg by default. GPG is obviously unlikely to switch for backwards compatibility, but egpg is a new tool, so would be nice to not clutter the user's HOME.

    [ -n "$XDG_CONFIG_HOME" ] || XDG_CONFIG_HOME="$HOME/.config"
    EGPG_DIR=$XDG_CONFIG_HOME/egpg

https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

**Comment by dashohoxha** [comment]
It makes sense not to clutter the user's HOME.

However `.gnupg` does not contain only configuration files, it also contains data files (keyring), runtime files (gpg-agent sockets), maybe cache files, etc. EGPG contains a copy of `.gnupg` inside it, so it contains all these kinds of files, not just config files.

It also makes sense to keep all the files of a certain program/application in the same place, instead of scattering them in separate directories. In this regard the XDG standard is not suitable. I would even say that the XDG standard is already outdated. We live in the time of apps, where each app tries to be as self contained and isolated from the rest of the host system as possible.

Is there any standard that supports this philosophy of self-containment of the apps?
